---

  - name: Switch off bahmni services from checkconfig
    service: name={{item}} state=stopped enabled=no
    with_items:
     - dcm4chee
     - bahmni-lab
     - bahmni-reports
     - bahmni-erp-connect
     - openmrs
     - openerp
     - pacs-integration


  - name: Check if bahmni-event-log-service Service Exists
    stat: path=/etc/init.d/bahmni-event-log-service
    register: service_status

  - name: Stop bahmni-event-log-service Service
    service: name=bahmni-event-log-service state=stopped enabled=no
    when: service_status.stat.exists


  - name: Stop Mysql Service
    service: name=mysqld state=stopped

  - name: Cleaning up old backup directory
    file:
      path=/var/lib/mysql_bkp
      state=absent

  - name: Taking backup of older data
    command: mv -f /var/lib/mysql /var/lib/mysql_bkp

  - name: Copy mysql config
    template:
      src=templates/my.cnf.j2
      dest=/etc/my.cnf
      backup=yes
      mode=755

  - name: Fetch mysql dump from slave master machine to preprod machine
    fetch: src=/opt/mysql-replication/mysql.tar  dest=/var/lib/ flat=yes fail_on_missing=yes
    sudo: no
    delegate_to: "{{ groups['slave'][0] }}"

  - name: untar to /var/lib
    unarchive: src=/var/lib/mysql.tar dest=/var/lib/ group=mysql owner=mysql

  - name: Remove auto.cnf
    command: mv /var/lib/mysql/auto.cnf /var/lib/mysql/auto.cnf_old

  - name: Start Mysql Service
    service: name=mysqld state=started enabled=true

  - name: start replication
    mysql_replication:
      mode: startslave
      login_user: "{{ mysql_root_user}}"
      login_password: "{{ mysql_root_password }}"
    ignore_errors: true
